#!/bin/bash


# If device is passed umount all mounts associated with it
if [ -b $1 ];then
  findmnt -nlo SOURCE |grep $1 | xargs -n1 udevil umount
else
# assume single mount point
  udevil umount $1
fi
