#!/bin/bash


#device
  #- dev part1 LABEL1
  #- dev part2 LABEL2
  #- dev part3 LABEL3

findmnt -l|grep '^/run/media'|
awk '{
  sub(/[0-9]+/,"",$2);
  dev[$2]=dev[$2]"\n  "$1
  }
END{
  for (X in dev) {
    print X dev[X]
  }
}'
